### PR TITLE
Indent percent literals: %w %W %i %I

### PR DESCRIPTION
**Pull request by stoodfarback**
zenspider#59

Comments/corrections welcome.

### CODE REVIEW

**Comment by jhelwig** [comment]
I'm not sure if `DELIM_MAP = { "(" => ")", "[" => "]", "{" => "}" }` is the best way to do this, since you can use a lot more than just that set of characters as delimiters with `%w`, `%W`, `%i`, and `%I`.

Ex:
```Ruby
irb(main):002:0> a = %W|asdflaksdjf asldfj asldfj|
=> ["asdflaksdjf", "asldfj", "asldfj"]
irb(main):003:0> a = %W/asdflaksdjf asldfj asldfj/
=> ["asdflaksdjf", "asldfj", "asldfj"]
irb(main):004:0> a = %W'asdflaksdjf asldfj asldfj'
=> ["asdflaksdjf", "asldfj", "asldfj"]
irb(main):011:0> a = %W@asdflaksdjf asldfj asldfj@
=> ["asdflaksdjf", "asldfj", "asldfj"]
```

I know there are more, so my examples are by no means an exhaustive list, and most of the possibilities probably aren't good ideas to use in the real world.  I'm not sure what the most maintainable way to account for this is.

**Comment by stoodfarback** [comment]
Nah, I accounted for that. `DELIM_MAP` is only for when the closing delimiter is different from the opening delimiter. Ie. `@plit_stack << (DELIM_MAP[delimiter] || delimiter)`, so it works fine with any delimiter symbols.

**Comment by jhelwig** [comment]
Yay! Sorry for the noise then.

**Comment by stoodfarback** [comment]
Hmm... Also, I only tested on ruby 2.2 and 2.1.5. Has `Ripper.lex` changed much?

**Comment by stoodfarback** [comment]
Tests pass for `2.0.0`.

However, `1.9.2` fails because `%i` and `%I` don't exist yet. Not sure what to do about that.

**Comment by stoodfarback** [comment]
Well, official support for ruby 1.9.3 ended today: https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

Maybe drop support as well?

**Comment by zenspider** [comment]
Sorry this took me so long to catch up on. This doesn't cleanly apply anymore. Can you rebase?

I can't readily drop support for 1.9 as much as I'd like to, simply because a ton of users still use it. Look to (most) linux's plodding ruby support for evidence.

**Comment by stoodfarback** [comment]
Rebase done.

**Comment by zenspider** [comment]
Can you split this test up per token, and then we can guard the `%i` case when on ruby < 2.

**Comment by zenspider** [comment]
anything?

**Comment by stoodfarback** [comment]
Updated. Also found a small bug when testing on 1.9, fixed that.

**Comment by zenspider** [comment]
OK. I've poked at this enough and even added some more unit tests. Merging. Thanks!

**Pull request merged**
