### PR TITLE
Fix brace indentation

### LINKED ISSUE #131: Method call after block not indented correctly.
In some cases chained method calls get indented incorrectly:

Expected: 
```ruby
  expect(subject).to receive(:api_call).with("subjectLookup", Search: "Food")
    .and_return { |m, *args| m.call(*args) }
    .once
```
got:

```ruby
  expect(subject).to receive(:api_call).with("subjectLookup", Search: "Food")
    .and_return { |m, *args| m.call(*args) }
  .once
```

### PR DESCRIPTION
**Pull request by muirrn**
I think this resolves #131 and #78 , and incorporates comment fix in #134

### CODE REVIEW

**Comment by zenspider** [comment]
I just merged #134 and now this has conflicts. Looks like you should drop 019e8d4 ?

**Comment by muirrn** [comment]
I force pushed and removed fixes that conflicted with #134. Sorry about that!

**Comment by zenspider** [comment]
Here's your fix reworked against current master:

https://gist.github.com/zenspider/b2d8874ce42b71ccc27c6132e5968d74

**Comment by muirrn** [comment]
Forced push again to integrate with new elisp tests.

**Comment by zenspider** [comment]
Thank you!

**Pull request merged**
