### PR TITLE
Add tests for `enh-ruby-deep-indent-construct` (#110)

### PR DESCRIPTION
**Pull request by knu**

### CODE REVIEW

**Comment by zenspider** [comment]
This conflicts... probably from one of your 2 previous PRs? fix and force push?

**Comment by zenspider** [comment]
mmm... I also have a conflict from the previous one to one of my commits... give me a sec.

**Comment by zenspider** [comment]
OK. I fixed my conflicts and pushed the rest of my commits... please fix this conflict and push again (with force, as necessary)

**Comment by knu** [comment]
Yes, that's simply because they add tests to the same file (test/enh-ruby-mode-test.el) and the conflict should be easy to resolve.

I've force-pushed after resolving it.

**Pull request merged**
