### PR TITLE
Steal `ruby-toggle-block` from ruby-mode

### PR DESCRIPTION
**Pull request by knu**

### CODE REVIEW

**Comment by zenspider** [comment]
OMG I LOVE YOU SO MUCH

**Comment by knu** [comment]
👍

**Comment by zenspider** [comment]
Shit... this fails a test: `enh-ruby-up-sexp-test` fails after this is merged.

**Comment by zenspider** [comment]
`enh-ruby-up-sexp-test    (wrong-type-argument integer-or-marker-p nil)`

**Comment by zenspider** [comment]
Unfortunately, while the tests fail... trying to debug this results in a parsing failure because the temporary buffer goes away so fast. Dunno what to do about that one.

**Comment by knu** [comment]
Hmm, I have no idea how this could possibly affect other parts of the module when it only adds a couple of functions and a key binding. 🤔

**Comment by knu** [comment]
There's also `ruby-toggle-string-quotes` but as I see it it might not be very easy to port it.  You could just say `(define-key enh-ruby-mode-map (kbd "C-c '") 'ruby-toggle-string-quotes)`, though. 😁

**Comment by zenspider** [comment]
Hrm... it's the test. Or side effects of running the test. If I comment out your test for toggle-block, then up-sexp passes... if I leave the test in, then it fails. Likewise, if I comment out your constant, your test fails and up-sexp passes... so maybe it has something to do with messing with regexp state?

**Comment by zenspider** [comment]
aand it is the SECOND call to toggle-block that is causing the failure...

**Comment by zenspider** [comment]
I got to go to bed... I'll take a whack at this in the morning but it's pretty hairy. I might have to roll it out.

If you have time, please run `rake` or `rake test:elisp` to reproduce. I broke it down to this:

```
(ert-deftest enh-ruby-toggle-block/brace ()
  (with-temp-enh-rb-string
   "7.times { |i|\n  puts \"number #{i+1}\"\n}\n"
   (enh-ruby-toggle-block)
   (buffer-should-equal "7.times do |i|\n  puts \"number #{i+1}\"\nend\n")))

(ert-deftest enh-ruby-toggle-block/do ()
  (with-temp-enh-rb-string
   "7.times do |i|\n  puts \"number #{i+1}\"\nend\n"
   (enh-ruby-toggle-block)
   (buffer-should-equal "7.times { |i| puts \"number #{i+1}\" }\n")))
```

and if you comment out the second one, the tests all pass.

**Comment by knu** [comment]
I don't know why, but adding `(sleep-for 0.5)` after `(erm-wait-for-parse)` in each of `with-temp-enh-rb-buffer` and `with-temp-enh-rb-string` seems to fix the failure.  Maybe `with-temp-enh-rb-buffer` doesn't wait enough?

**Comment by zenspider** [comment]
the wait on `erm-wait-for-parse` doesn't seem to matter... The sleep-for can be pushed down to just `up-sexp` and made much smaller... so at least now it isn't bothersome and is clearly something to do with the tests' architecture and not (directly) the implementation. I still think it is wrong how much the code is looking at properties instead of actually parsing things, but I can't deal with that right now.

This will do, and will allow me to spend time on the `erm-wait-for-parse` separately.

**Pull request merged**
