### PR TITLE
Add a new custom `enh-ruby-deep-indent-construct`

### PR DESCRIPTION
**Pull request by knu**
Setting this to nil means constructs such as if, def, class and module are not deep-indented.

```ruby
  private def some_method
    do_this
    do_that
  end

  x = if y
    p
  else
    q
  end
```

When non-nil (default):

```ruby
  private def some_method
            do_this
            do_that
          end

  x = if y
        p
      else
        q
      end
```

This should address #67 and #108.

### CODE REVIEW

**Comment by zenspider** [comment]
Thanks @knu! I'm happy to merge this... but can I talk you into writing a couple tests for it? I probably won't use this so I won't know if/when it regresses.

**Comment by zenspider** [comment]
Maybe steal from https://github.com/ento/enhanced-ruby-mode/commit/bd9a81c05d1e3a3ca2a2aa2ec44abace0fdbfb8c#diff-3520f4c76a463ca6d4d1a41ccd735006R102 ?

**Comment by zenspider** [comment]
I'm merging this now... tests would be lovely tho.

**Comment by knu** [comment]
Thanks!  This is just a quick hack that happens to work well for most typical cases, so I agree it needs some regression tests.

Actually, I still have no idea what variable names like `bc` or `pc` stand for. 😇

**Comment by zenspider** [comment]
Neither do I. 😛

**Pull request merged**
