### PR TITLE
Fix deep indent paren

### LINKED ISSUE #90: Deep indent parent only for paren-wrapped statements
I'm not sure if this is a configuration error on my part or if `enh-ruby-mode-deep-indent-paren` doesn't do what I expected it to do.

This is how I want the code to look:

``` ruby
RailsModel.create(:some_attr => 'a_value',
                  :secret    => 42, 
                  :works     => true)

literal_array = [
  :contains,
  :some,
  :keys
]
```

If I enable `enh-ruby-mode-deep-indent-paren` this is what I get:

``` ruby
RailsModel.create(:some_attr => 'a_value',
                  :secret    => 42,
                  :works     => true)

literal_array = [
         :contains,
         :some,
         :keys
        ]
```

If I disable that then I get this:

``` ruby
RailsModel.create(:some_attr => 'a_value',
  :secret    => 42,
  :works     => true)

literal_array = [
  :contains,
  :some,
  :keys
]
```

Is there something I am doing wrong? Or is there a way to get my desired indentation from this?

### PR DESCRIPTION
**Pull request by muirrn**
Resolves #90

### CODE REVIEW

**Comment by muirrn** [comment]
I did it as a separate commit, so if you look at the commits one by one it will be easier.

**Comment by zenspider** [comment]
I don't want it because it causes conflicts.

**Comment by zenspider** [comment]
It appears your change breaks two tests:

```
   FAILED  enh-ruby-indent-array-of-strings/deep
   FAILED  enh-ruby-indent-hash/deep
```

Looks like it is not respecting deep-indent in cases like:

```ruby
words = [
  'moo'
]
# or
c = {
  a: a,
  b: b
}
```

**Comment by muirrn** [comment]
I think those cases are not supposed to deep indent because there is no stuff on the same line after the opening. See ruby-mode behavior in https://github.com/zenspider/enhanced-ruby-mode/issues/90#issuecomment-159238548

**Comment by muirrn** [comment]
I have removed the reformatting and integrated the tests with your changes.

**Comment by zenspider** [comment]
Thank you!

**Pull request merged**
